@startuml mascota 



class Carne
class Animal


package Cocina{
    class Cocina{
        +comida:Comida
    }
    class Comida
}

package Habitacion{
    class Habitacion
    class Ropa
    class Cama
}

package Baño{
    class Baño{
        -agua:Agua
        -medicina:Medicina
        -inodoro:Inodoro
        -jabon:Jabon
    }
    class Agua
    class Inodoro
    class Jabon
    class Medicina
}

package Mascota{
    class Mascota{
        -sentimiento:Sentimiento
        +Habitacion();
        +Cocina();
        +Baño();
    }
    class Alimento
}

package Juguete{
    class Juguete
    class Pelota
    class Carro
}

package Sentimiento{
    class Sentimiento
    class Alegria
    class Tristeza
    class Enfermo
}


Mascota "1" *-- "1.." Sentimiento 
Alegria --|> Sentimiento
Tristeza --|> Sentimiento
Enfermo --|> Sentimiento
Mascota "1" o-- "1" Habitacion 
Habitacion "1" *-- "*" Ropa 
Habitacion "1" *-- "1" Cama 
Mascota --|> Animal 
Carne--|> Alimento 
Alimento "*" --o "1" Mascota 
Mascota "1" o-- "1" Juguete 
Mascota "1" o-- "1" Cocina 
Cocina "1" *-- "1" Comida 
Pelota --|> Juguete
Carro --|> Juguete
Mascota  o-- Baño 
Baño "1" *-- "1" Jabon 
Baño "1" *-- "1" Agua
Baño "1" *-- "1" Inodoro
Baño "1" *-- "1" Medicina
Carne --|> Alimento
Alimento "1" --o "1" Mascota 


@enduml 